# Generated by Django 4.0.1 on 2022-01-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=128, verbose_name='Название предмета')),
                ('week_day', models.CharField(max_length=1, verbose_name='День недели')),
                ('pair_number', models.CharField(max_length=1, verbose_name='Номер пары')),
                ('building_id', models.CharField(max_length=2, verbose_name='Корпус')),
                ('floor_id', models.CharField(max_length=2, verbose_name='Этаж')),
                ('classroom_id', models.CharField(max_length=2, verbose_name='Аудитория')),
            ],
        ),
    ]
